In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv("../../datasets/loan_dataset.csv", encoding='latin1')

dataset.head(5)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,NaN,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,Rural,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,Semiurban,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,Urban,Y
3,LP1004,NaN,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,Urban,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,Rural,N

In [2]:
dataset.isnull().sum()

Loan_ID              0
Gender             374
Married            322
Dependend          195
Education            0
Self_Employment    346
Application          0
Coapplication        0
LoanAmount           0
Credit_History     367
Property_Area        0
Loan_status          0
dtype: int64

In [3]:
dataset["Gender"] = dataset["Gender"].fillna(dataset["Gender"].mode()[0])

In [4]:
dataset["Married"] = dataset["Married"].fillna(dataset["Married"].mode()[0])

In [5]:
en_data = dataset[["Gender", "Married"]]

### Method 1

In [6]:
pd.get_dummies(en_data)

      Gender_Female  Gender_Male  Married_No  Married_Yes
0             False         True        True        False
1             False         True       False         True
2              True        False       False         True
3             False         True       False         True
4              True        False       False         True
...             ...          ...         ...          ...
1045          False         True       False         True
1046          False         True        True        False
1047          False         True       False         True
1048          False         True       False         True
1049          False         True       False         True

[1050 rows x 4 columns]

In [7]:
pd.get_dummies(en_data).info()

<class 'pandas.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  1050 non-null   bool
 1   Gender_Male    1050 non-null   bool
 2   Married_No     1050 non-null   bool
 3   Married_Yes    1050 non-null   bool
dtypes: bool(4)
memory usage: 4.2 KB

### Method 2

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe = OneHotEncoder()
ar = ohe.fit_transform(en_data).toarray()
ohe.get_feature_names_out()

array(['Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes'],
      dtype=object)

In [10]:
pd.DataFrame(ar, columns=["Gender_Female", "Gender_Male", "Married_No", "Married_Yes"])

      Gender_Female  Gender_Male  Married_No  Married_Yes
0               0.0          1.0         1.0          0.0
1               0.0          1.0         0.0          1.0
2               1.0          0.0         0.0          1.0
3               0.0          1.0         0.0          1.0
4               1.0          0.0         0.0          1.0
...             ...          ...         ...          ...
1045            0.0          1.0         0.0          1.0
1046            0.0          1.0         1.0          0.0
1047            0.0          1.0         0.0          1.0
1048            0.0          1.0         0.0          1.0
1049            0.0          1.0         0.0          1.0

[1050 rows x 4 columns]

In [11]:
ohe = OneHotEncoder(drop="first") # by using drop first metho first columsn are going to be deleted in our case Gender_Female & Married_No will be delted 
ar = ohe.fit_transform(en_data).toarray() #convert categorical data into numberical data
ar

array([[1., 0.],
       [1., 1.],
       [0., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [1., 1.]], shape=(1050, 2))

In [12]:
ohe.get_feature_names_out()

array(['Gender_Male', 'Married_Yes'], dtype=object)

In [13]:
pd.DataFrame(ar, columns=["Gender_Male", "Married_Yes"])

      Gender_Male  Married_Yes
0             1.0          0.0
1             1.0          1.0
2             0.0          1.0
3             1.0          1.0
4             0.0          1.0
...           ...          ...
1045          1.0          1.0
1046          1.0          0.0
1047          1.0          1.0
1048          1.0          1.0
1049          1.0          1.0

[1050 rows x 2 columns]

In [14]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,Male,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,Rural,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,Semiurban,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,Urban,Y
3,LP1004,Male,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,Urban,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,Rural,N