### Ordinal Encoding

 we can perform ordinal encoding by two ways 1. Cyclic Line 2. Map Function

#### Cyclic Line Method

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"Size": ["s", "m", "l", "xl", "s", "m", "l", "s", "s", "l", "sl", "m"]})
df.head(5)

  Size
0    s
1    m
2    l
3   xl
4    s

In [3]:
ord_data = [["s", "m", "l", "xl", "sl"]]

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories=ord_data) 
# oe = OrdinalEncoder() its called Automatic Categories detection
oe.fit(df[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl', 'sl']])

In [6]:
oe.transform(df[["Size"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [4.],
       [1.]])

In [8]:
df["Size_en"] = oe.transform(df[["Size"]])

In [9]:
df

   Size  Size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   sl      4.0
11    m      1.0

#### Map Function Method

In [12]:
ord_data1 = {"s": 0, "m":1, "l":2, "x1":3}

In [13]:
df["Size"].map(ord_data1)

0     0.0
1     1.0
2     2.0
3     NaN
4     0.0
5     1.0
6     2.0
7     0.0
8     0.0
9     2.0
10    NaN
11    1.0
Name: Size, dtype: float64

In [14]:
df["Size_en_map"] = df["Size"].map(ord_data1)

In [15]:
df

   Size  Size_en  Size_en_map
0     s      0.0          0.0
1     m      1.0          1.0
2     l      2.0          2.0
3    xl      3.0          NaN
4     s      0.0          0.0
5     m      1.0          1.0
6     l      2.0          2.0
7     s      0.0          0.0
8     s      0.0          0.0
9     l      2.0          2.0
10   sl      4.0          NaN
11    m      1.0          1.0

In [16]:
dataset = pd.read_csv(r"D:\Practice\JupitorNoteBookPrograms\datasets\loan_dataset.csv")

In [17]:
dataset.head(5)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,NaN,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,Rural,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,Semiurban,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,Urban,Y
3,LP1004,NaN,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,Urban,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,Rural,N

In [18]:
dataset["Property_Area"].unique()

array(['Rural', 'Semiurban', 'Urban'], dtype=object)

In [19]:
dataset["Property_Area"].fillna(dataset["Property_Area"].mode()[0], inplace=True)

C:\Users\Tushar Nile\AppData\Local\Temp\ipykernel_6132\2436976519.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Property_Area"].fillna(dataset["Property_Area"].mode()[0], inplace=True)

In [20]:
en_data_ord = [['Rural', 'Semiurban', 'Urban']]

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
oen = OrdinalEncoder(categories=en_data_ord)

In [23]:
oen.fit_transform(dataset[["Property_Area"]])

array([[0.],
       [1.],
       [2.],
       ...,
       [1.],
       [1.],
       [2.]], shape=(1050, 1))

In [24]:
dataset["Property_Area"] = oen.fit_transform(dataset[["Property_Area"]])

In [26]:
dataset.head(100)

,Loan_ID,Gender,Married,Dependend,Education,Self_Employment,Application,Coapplication,LoanAmount,Credit_History,Property_Area,Loan_status
0,LP1001,NaN,No,3+,Graduate,Yes,5745.07,1889.39,155.91,NaN,0.0,N
1,LP1002,Male,Yes,3+,Not Grad,Yes,7284.54,1812.68,120.63,NaN,1.0,Y
2,LP1003,Female,Yes,1,Not Grad,No,7368.82,2613.95,111.22,0.0,2.0,Y
3,LP1004,NaN,Yes,1,Not Grad,NaN,5813.84,1629.27,111.37,0.0,2.0,Y
4,LP1005,Female,Yes,NaN,Not Grad,NaN,5362.94,469.38,61.00,0.0,0.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP1096,Female,NaN,1,Not Grad,Yes,2071.87,1878.57,153.53,1.0,1.0,N
96,LP1097,NaN,No,0,Not Grad,NaN,5421.49,1501.84,121.68,NaN,1.0,N
97,LP1098,NaN,NaN,NaN,Not Grad,NaN,4260.50,1528.51,163.98,0.0,2.0,N
98,LP1099,Female,NaN,2,Graduate,No,5535.52,1445.67,165.98,1.0,1.0,Y
99,LP1100,Male,No,3+,Graduate,NaN,5460.95,2650.29,155.19,0.0,2.0,N