### One Hot Encoding

In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Aman", "Sita", "Neha"],
    "Gender": ["Male", "Male", "Female", "Female"],
    "Age": [23, 25, 22, 24]
}

df = pd.DataFrame(data)

df.head()

    Name  Gender  Age
0  Rahul    Male   23
1   Aman    Male   25
2   Sita  Female   22
3   Neha  Female   24

In [2]:
encoded = pd.get_dummies(df["Gender"])
encoded

   Female   Male
0   False   True
1   False   True
2    True  False
3    True  False

In [3]:
encoded = pd.get_dummies(df["Gender"], dtype=int)
encoded

   Female  Male
0       0     1
1       0     1
2       1     0
3       1     0

In [4]:
df = pd.concat([df, encoded], axis=1)
df

    Name  Gender  Age  Female  Male
0  Rahul    Male   23       0     1
1   Aman    Male   25       0     1
2   Sita  Female   22       1     0
3   Neha  Female   24       1     0

In [5]:
df = df.drop("Gender", axis=1)
df

    Name  Age  Female  Male
0  Rahul   23       0     1
1   Aman   25       0     1
2   Sita   22       1     0
3   Neha   24       1     0

### Short Method

In [6]:
# df = pd.get_dummies(df, columns=["Gender"])