### One Hot Encoding using Scikit learn

In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Aman", "Sita", "Neha"],
    "Gender": ["Male", "Male", "Female", "Female"],
    "Age": [23, 25, 22, 24]
}

df = pd.DataFrame(data)
df

    Name  Gender  Age
0  Rahul    Male   23
1   Aman    Male   25
2   Sita  Female   22
3   Neha  Female   24

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[["Gender"]]).toarray()
encoded

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [4]:
columns = encoder.get_feature_names_out(["Gender"])
columns

array(['Gender_Female', 'Gender_Male'], dtype=object)

In [5]:
encoded_df = pd.DataFrame(encoded, columns=columns)
encoded_df

   Gender_Female  Gender_Male
0            0.0          1.0
1            0.0          1.0
2            1.0          0.0
3            1.0          0.0

In [6]:
df = pd.concat([df, encoded_df], axis=1)
df

    Name  Gender  Age  Gender_Female  Gender_Male
0  Rahul    Male   23            0.0          1.0
1   Aman    Male   25            0.0          1.0
2   Sita  Female   22            1.0          0.0
3   Neha  Female   24            1.0          0.0

In [7]:
df = df.drop("Gender", axis=1)
df

    Name  Age  Gender_Female  Gender_Male
0  Rahul   23            0.0          1.0
1   Aman   25            0.0          1.0
2   Sita   22            1.0          0.0
3   Neha   24            1.0          0.0

In [8]:
'''
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[["Gender"]])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["Gender"]))

df = pd.concat([df.drop("Gender", axis=1), encoded_df], axis=1)
'''

'\nfrom sklearn.preprocessing import OneHotEncoder\nimport pandas as pd\n\nencoder = OneHotEncoder(sparse_output=False)\n\nencoded = encoder.fit_transform(df[["Gender"]])\n\nencoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["Gender"]))\n\ndf = pd.concat([df.drop("Gender", axis=1), encoded_df], axis=1)\n'