In [1]:
import pandas as pd

# read csv file
df = pd.read_csv('../../datasets/players_20.csv', encoding='latin1')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [2]:
df.head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### Selecting with a single value
iloc[row_position, column_position]

In [3]:
# get the height of L.Messi
df.iloc[0, 3]

np.int64(170)

In [4]:
# get the weight of Cristiano Ronaldo
df.iloc[1, 4]

np.int64(83)

In [5]:
# get all rows inside the 'height_cm column'
df.iloc[:, 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [6]:
# get all columns that correspond to the index 'L. Messi'
df.iloc[0, :]

long_name      Lionel AndrÃ©s Messi Cuccittini
age                                         32
dob                                 1987-06-24
height_cm                                  170
weight_kg                                   72
nationality                          Argentina
club                              FC Barcelona
Name: L. Messi, dtype: object

### Selecting with a list of values

In [7]:
# get all data about L.Messi and Cristiano Ronaldo
df.iloc[[0, 1]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [8]:
# get the height of L.Messi and Cristiano Ronaldo
df.iloc[[0, 1], 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [9]:
# get the height and weight of L.Messi
df.iloc[0, [3, 4]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [10]:
# get height and weight of L.Messi and Cristiano Ronaldo
df.iloc[[0, 1], [3, 4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

### Selecting a range of data with a slice
start:stop (Note that the start is included but the stop is excluded)

In [11]:
# slice column labels age/club
# players = ['L. Messi', 'Cristiano Ronaldo']
players = [0, 1]

df.iloc[players, 1:7] # age:club+1

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [12]:
# slice index labels (top1 to top10 player)
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4]

# get top1 and top10 player name
df.iloc[0:10, columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. ModriÄ          33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

### Selecting with conditions
iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a Series into a boolean list.

In [13]:
# one condition: select player with height above 180cm
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4]

df.iloc[list(df['height_cm']>180), columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [14]:
# multiple conditions: select player with height above 180cm from Argentina
df.iloc[list((df['height_cm']>180) & (df['nationality']=='Argentina')), :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. HiguaÃ­n,Gonzalo Gerardo HiguaÃ­n,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,NicolÃ¡s HernÃ¡n Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,GerÃ³nimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,TomÃ¡s Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,JoaquÃ­n Hass,21,1998-03-27,186,88,Argentina,Club AtlÃ©tico ColÃ³n
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club AtlÃ©tico HuracÃ¡n
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,NicolÃ¡s Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors