In [1]:
import pandas as pd

# read csv file
df = pd.read_csv('../../datasets/players_20.csv', encoding='latin1')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [2]:
# show dataframe
df.head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### Drop Row

In [3]:
# drop one row
# axis parameter
df.drop('L. Messi', axis=0)

# index parameter
df.drop(index=['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [4]:
# drop two or more rows and update data (inplace=True)
df.drop(['L. Messi', 'Cristiano Ronaldo'], axis=0, inplace=True)

In [5]:
df.head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona

### Drop Columns

In [6]:
# drop one column
# axis parameter
df.drop('long_name', axis=1)

# index parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [7]:
# drop column by position/index (drop last column)
df.drop(df.columns[[-1]], axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
M. ter Stegen,Marc-AndrÃ© ter Stegen,27,1992-04-30,187,85,Germany
...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR

In [8]:
# drop two or more columns and update data (inplace=True)
df.drop(['long_name', 'dob'], axis=1, inplace=True)

In [9]:
df.head(5)

               age  height_cm  weight_kg nationality                 club
short_name
Neymar Jr       27        175         68      Brazil  Paris Saint-Germain
J. Oblak        26        188         87    Slovenia     AtlÃ©tico Madrid
E. Hazard       28        175         74     Belgium          Real Madrid
K. De Bruyne    28        181         70     Belgium      Manchester City
M. ter Stegen   27        187         85     Germany         FC Barcelona