In [1]:
import pandas as pd

# read csv file
df = pd.read_csv('../../datasets/players_20.csv', encoding='latin1')

# set index
df.set_index('short_name', inplace=True)

# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [2]:
df.head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

### copy()
### deep = True

In [3]:

# deep=True by default (Modifications to the data or indices of the copy will not be reflected in the original object )
df_copy = df.copy()

In [4]:

# update value in original dataframe
df.loc['L. Messi', 'height_cm'] = 180

In [5]:

# copy vs original dataframe
df
df_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### deep = False

In [6]:
# deep=False (Any changes to the data of the original will be reflected in the shallow copy and vice versa)
df_shallow_copy = df.copy(deep=False)

In [7]:

# update value in original dataframe
df.loc['Cristiano Ronaldo', 'height_cm'] = 200

In [8]:

# shallow copy vs original dataframe
df
df_shallow_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### Simple assignment

In [9]:

# make a copy
df_new_copy = df

In [10]:
# update value in original dataframe
df.loc['Neymar Jr', 'height_cm'] = 190

In [11]:

# copy vs original dataframe
df
df_new_copy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel AndrÃ©s Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,AtlÃ©tico Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,éµå¸,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,å¼ å¨,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,æ±ªæµ·å¥,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,æ½åæ,26,1993-01-11,182,78,China PR,Hebei China Fortune FC